name:  Testing github workflows in branch lab1

on: push
      branches:
        - anotherlab1

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Étape 1 - Initialisation
        run: echo "Initialisation"

      - name: Étape 2 - Récupération du code
        run: echo "Récupération du code"

      - name: Étape 3 - Build
        run: echo "Build de l'application"

      - name: Étape 4 - Test
        run: echo "Exécution des tests"

      - name: Étape 5 - Packaging
        run: echo "Packaging de l'application"

      - name: Étape 6 - Fin du pipeline
        run: echo "Fin du pipeline"

      - name: Job terminé
        run: echo "Complete job"
